SLStudio.Utils.RemoveHighlighting(get_param('ControllerTestbench', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_ControllerTestbench', 'handle'));
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/t', 1, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/t1', 1, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Hidden Layer (2 Neurons)/transpose', 1, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/Add', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/Compare To Constant', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/transpose', 1, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/Product', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/Product1', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/Product2', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/Product3', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/Product4', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/Product5', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/Product6', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/Product7', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/concatenate', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/concatenate1', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/PipelineRegister', 0, 1, '');
annotate_port('gm_ControllerTestbench/Controller_equiv_DC_motor1/PI_Ctrl_float_speed/Reinforcement Learning1/Subsystem Reference2/Input Layer (4 Neurons)/HwModeRegister73', 1, 1, '');
